Make using user shell optional
osrf/rocker pull request #185
Opened 2022-07-09 09:49 UTC by rcywongaa

2022-07-12 06:43 UTC, tfoote requested changes
Thanks for putting together the PR for this.

There's definitely a case to be made that the default could be the default shell inside the container versus the default shell from the outside. In the cases that I've been supporting they've usually been the same. But for the use cases when I'm trying to replicate the user's development experience inside the container reproducing their shell inside is useful too. (Aka you use `--home` with `--user` you get you whole shell environment with all your settings etc.) As this is the primary use case I've been targeting I'd like to keep that as the default. 

With the way you've laid out the logic there's currently only two possible shells. Either the user's external shell or the internal default. Whereas I was proposing you have the user's external shell, or alternatively you can specify a specific shell which could be any shell you want. This mirrors the `override-username` where you either get the external username or you can force any username you want based on knowledge of your target. 

In general if you're using zsh or some other shell externally I would suggest that you consider also making a small extension which will inject zsh into the container you're using that way you can have your preferred shell too when you use rocker. The other possible extension would be to have a `--user-no-set-shell` option. Or it maybe could be not set if the override option is explicitly set to an empty string. 

In the larger picture I'd like to get to having some rocker config file format to help people keep their command lines less verbose and set defaults for their operations.

2022-07-12 06:43 UTC, tfoote commented on src/rocker/extensions.py
> +        parser.add_argument('--use-user-shell',
I proposed `--user-override-shell` 

The beginning of the argument matches the plugin name which I definitely want. All arguments relating to that plugin should start with `--user` for grouping and visibility.

2022-07-12 06:44 UTC, tfoote commented
Oh sorry I also forgot to mention that I'd like to also make sure to add coverage of this extra option in the unit tests before merging.

2022-07-12 20:12 UTC, rcywongaa commented
My (probably incorrect) use case of `--user` is to simply avoid having to manually create a non-root user so that any files generated within the container ends up having the same owner as the host.  Hence my settings were more towards create the user and nothing more.  My zsh is heavily customized with many plugins which probably doesn't make sense to replicate in the container.

Anyway, I understand the original intention.  I guess most container's default / available shell is well known (`bin/sh`) anyway

2022-07-13 22:40 UTC, tfoote approved these changes
Thanks for the updates. It looks good to me. 

Your use case isn't incorrect. That is a primary function of the `--user` option, it's more of a prioritization of the different use cases.

2022-07-13 22:40 UTC, merged