Add support for ulimit flag
osrf/rocker pull request #291
Opened 2024-10-09 22:01 UTC by fpadula

Hi, this PR adds support for the `ulimit` flag (https://docs.docker.com/reference/cli/docker/container/run/#ulimit). This flag is useful when running ROS 1 containers in machines with high `nofile` limits (default in Arch Linux) since not limiting this causes system crashes (please read https://answers.ros.org/question/336963/rosout-high-memory-usage/ for more info).

This PR adds:
- `Ulimit` class that extends  `RockerExtension` to add support for the `--ulimit` flag in Docker
- Checks for appropriate syntax using regex
- Descriptive message when using `help` command and when raising argument type exception (similar to the `Volume` extension)
- Basic unit tests

2024-10-16 16:25 UTC, tfoote requested changes
Thanks for a well written plugin with good coverage. I have one request for the tests to improve the error capture if they fail. Otherwise this looks good to me.

2024-10-16 16:25 UTC, tfoote commented on test/test_ulimit.py
> +    def _is_arg_translation_ok(self, mock_cliargs, expected):
Thanks for comprehensive tests. Could you change this function to return a tuple of the success and message as a tuple that can then be passed to assertFalse or assertTrue so that the message gets captured in the unit test report not just in the console output. 

The return would be `(is_ok, message_string)`

2024-10-16 16:25 UTC, tfoote commented on test/test_ulimit.py
> +        self.assertTrue(self._is_arg_translation_ok(mock_cliargs, expected))
```suggestion
        self.assertTrue(*self._is_arg_translation_ok(mock_cliargs, expected))
```
With the addition of the tuple return of the helper method this will expand the results into the assertTrue arguments.

2024-10-17 23:28 UTC, fpadula commented
> Thanks for a well written plugin with good coverage. I have one request for the tests to improve the error capture if they fail. Otherwise this looks good to me.

Thanks for the feedback! I've addressed the requests on the latest commit.

2024-10-29 22:54 UTC, tfoote approved these changes
Thanks for the iteration. It looks good to me now.

2024-10-29 23:15 UTC, merged